version: 0.1
os: linux
files:
    - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: stop_server
    timeout: 30
    runas: root

phases:
  build:
    commands:
      - sudo su
      - java -jar blind-jobs-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - java -jar blind-jobs-0.0.1-SNAPSHOT.jar
  discard-paths: yes
