version: 0.1
# os: linux
# files:
#     - source: /
#     destination: /var/www/html/
# hooks:
#   BeforeInstall:
#     - location: stop_server
#     timeout: 30
#     runas: root

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - java -jar blind-jobs-0.0.1-SNAPSHOT.jar
  discard-paths: yes
