spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:file:./database/dev/backup_data;MODE=MySQL
    username: admin
    password: admin
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging.file:
  path: ./home/user
  name: my.log

server.port: 5000